# Uncomment the next line to define a global platform for your project
platform :ios, '10.4'
use_frameworks!
target 'delivery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # RxSwift  
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  # Swinject
  pod 'Swinject'
  pod 'SwinjectStoryboard'

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end

target 'deliveryTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'

    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
end

